//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.ENTREGAS = new HashSet<ENTREGAS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_CONDICIONIVA { get; set; }
        public string CLI_CF_TIPODOC { get; set; }
        public string CLI_CF_DOC { get; set; }
        public string CLI_CF_CUIL { get; set; }
        public string CLI_CF_NOMBRE { get; set; }
        public string CLI_CF_APELLIDO { get; set; }
        public string CLI_CF_EMAIL { get; set; }
        public string CLI_CF_TELEFONO { get; set; }
        public string CLI_CF_DIRECCION { get; set; }
        public string CLI_CF_LOCALIDAD { get; set; }
        public string CLI_CF_PROVINCIA { get; set; }
        public string CLI_CF_PAIS { get; set; }
        public Nullable<int> CLI_CF_CODPOSTAL { get; set; }
        public string CLI_RI_CUIT { get; set; }
        public string CLI_RI_RAZONSOCIAL { get; set; }
        public string CLI_RI_DIRECCION { get; set; }
        public string CLI_RI_LOCALIDAD { get; set; }
        public string CLI_RI_PROVINCIA { get; set; }
        public string CLI_RI_PAIS { get; set; }
        public Nullable<int> CLI_RI_CODPOSTAL { get; set; }
        public string CLI_RI_CON_TIPODOC { get; set; }
        public string CLI_RI_CON_DOC { get; set; }
        public string CLI_RI_CON_NOMBRE { get; set; }
        public string CLI_RI_CON_APELLIDO { get; set; }
        public string CLI_RI_CON_EMAIL { get; set; }
        public string CLI_RI_CON_TELEFONO { get; set; }
    
        public virtual ICollection<ENTREGAS> ENTREGAS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
