//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTES
    {
        public CLIENTES()
        {
            this.ENTREGAS = new HashSet<ENTREGAS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
            this.VENTAS = new HashSet<VENTAS>();
            this.RESERVAS = new HashSet<RESERVAS>();
        }
    
        public int CLI_ID { get; set; }
        public string CLI_DOC { get; set; }
        public string CLI_CUIL { get; set; }
        public string CLI_NOMBRE { get; set; }
        public string CLI_APELLIDO { get; set; }
        public string CLI_EMAIL { get; set; }
        public string CLI_TELEFONO { get; set; }
        public string CLI_DIRECCION { get; set; }
        public string CLI_LOCALIDAD { get; set; }
        public string CLI_PROVINCIA { get; set; }
        public string CLI_PAIS { get; set; }
        public string CLI_RI_CUIT { get; set; }
        public string CLI_RI_RAZONSOCIAL { get; set; }
        public string CLI_RI_DIRECCION { get; set; }
        public string CLI_RI_LOCALIDAD { get; set; }
        public string CLI_RI_PROVINCIA { get; set; }
        public string CLI_RI_PAIS { get; set; }
        public Nullable<int> TC_ID { get; set; }
        public string CLI_CODPOSTAL { get; set; }
        public string CLI_RI_CODPOSTAL { get; set; }
        public Nullable<int> TD_ID { get; set; }
        public string CLI_RI_TELEFONO { get; set; }
        public string CLI_RI_EMAIL { get; set; }
    
        public virtual TIPO_CLIENTE TIPO_CLIENTE { get; set; }
        public virtual TIPO_DOCUMENTO TIPO_DOCUMENTO { get; set; }
        public virtual ICollection<ENTREGAS> ENTREGAS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
    }
}
