//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADOS
    {
        public EMPLEADOS()
        {
            this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();
            this.RESERVAS = new HashSet<RESERVAS>();
            this.USOS_INTERNOS = new HashSet<USOS_INTERNOS>();
            this.VENTAS = new HashSet<VENTAS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int EMP_ID { get; set; }
        public Nullable<int> SUC_ID { get; set; }
        public Nullable<int> EMP_CODPOSTAL { get; set; }
        public string EMP_NOMBRE { get; set; }
        public string EMP_APELLIDO { get; set; }
        public string EMP_EMAIL { get; set; }
        public string EMP_USER { get; set; }
        public string EMP_PASSWORD { get; set; }
        public string EMP_TIPO { get; set; }
        public string EMP_DIRECCION { get; set; }
        public string EMP_TELEFONO { get; set; }
        public string EMP_DNI { get; set; }
        public string EMP_APELLIDO_NOMBRE { get; set; }
    
        public virtual SUCURSALES SUCURSALES { get; set; }
        public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ICollection<USOS_INTERNOS> USOS_INTERNOS { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
