//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ENTREGAS
    {
        public Nullable<int> FEC_ID { get; set; }
        public int ENT_ID { get; set; }
        public Nullable<int> MONTO { get; set; }
        public Nullable<int> VEN_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual FECHAS FECHAS { get; set; }
        public virtual VENTAS VENTAS { get; set; }
    }
}
