//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.USUARIOS = new HashSet<USUARIOS>();
        }
    
        public int ESTADO { get; set; }
        public string ESTADO_DESC { get; set; }
    
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
    }
}
