//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTADOS
    {
        public ESTADOS()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
            this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();
            this.RESERVAS = new HashSet<RESERVAS>();
            this.USUARIOS = new HashSet<USUARIOS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int ES_ID { get; set; }
        public string ES_DESCRIPCION { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ICollection<USUARIOS> USUARIOS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
