//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FECHAS
    {
        public FECHAS()
        {
            this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();
            this.RESERVAS = new HashSet<RESERVAS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int FEC_ID { get; set; }
        public Nullable<System.DateTime> FEC_FECHA { get; set; }
        public Nullable<int> FEC_NRODIA { get; set; }
        public string FEC_NOMBREDIA { get; set; }
        public Nullable<int> FEC_NROMES { get; set; }
        public string FEC_NOMBREMES { get; set; }
        public Nullable<int> FEC_ANIO { get; set; }
        public Nullable<int> FEC_ANIOMES { get; set; }
    
        public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
