//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGENES
    {
        public IMAGENES()
        {
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int IMG_ID { get; set; }
        public string IMG_NAME { get; set; }
        public byte[] IMG_IMAGE { get; set; }
        public Nullable<int> VEH_ID { get; set; }
    
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
