
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Octopus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class MARCAS
{

    public MARCAS()
    {

        this.PRESUPUESTOS = new HashSet<PRESUPUESTOS>();

        this.VEHICULOS = new HashSet<VEHICULOS>();

        this.VENTAS = new HashSet<VENTAS>();

    }


    public int MAR_ID { get; set; }

    public string MAR_DESCRIPCION { get; set; }



    public virtual ICollection<PRESUPUESTOS> PRESUPUESTOS { get; set; }

    public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }

    public virtual ICollection<VENTAS> VENTAS { get; set; }

}

}
