//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVAS
    {
        public int RES_ID { get; set; }
        public Nullable<int> VEH_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> RES_SENIA { get; set; }
        public Nullable<int> RES_VALOR_PACTADO { get; set; }
        public Nullable<int> FEC_ID_FIN { get; set; }
        public int RES_ESTADO { get; set; }
        public Nullable<int> FEC_ID_INICIO { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public Nullable<int> SUC_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual FECHAS FECHAS { get; set; }
        public virtual FECHAS FECHAS1 { get; set; }
        public virtual SUCURSALES SUCURSALES { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
    }
}
