//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SERVICIOS
    {
        public int SER_ID { get; set; }
        public string SER_DESCRIP { get; set; }
        public Nullable<int> SER_COSTO { get; set; }
        public Nullable<int> SUC_ID { get; set; }
    
        public virtual SUCURSALES SUCURSALES { get; set; }
    }
}
