//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SUCURSALES
    {
        public SUCURSALES()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
            this.VEHICULOS = new HashSet<VEHICULOS>();
        }
    
        public int SUC_ID { get; set; }
        public string SUC_DESCRIP { get; set; }
    
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }
    }
}
