
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Octopus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class TIPO_COMBUSTIBLES
{

    public TIPO_COMBUSTIBLES()
    {

        this.VEHICULOS = new HashSet<VEHICULOS>();

    }


    public int TCOM_ID { get; set; }

    public string TCOM_DESCRIPCION { get; set; }



    public virtual ICollection<VEHICULOS> VEHICULOS { get; set; }

}

}
