//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPO_DOCUMENTO
    {
        public TIPO_DOCUMENTO()
        {
            this.CLIENTES = new HashSet<CLIENTES>();
        }
    
        public int TD_ID { get; set; }
        public string TD_DESCRIPCION { get; set; }
    
        public virtual ICollection<CLIENTES> CLIENTES { get; set; }
    }
}
