//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USOS_INTERNOS
    {
        public int USO_ID { get; set; }
        public Nullable<int> VEH_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public string USO_DESCRIP { get; set; }
        public Nullable<System.DateTime> USO_FECHA_INI { get; set; }
        public Nullable<System.DateTime> USO_FECHA_FIN { get; set; }
    
        public virtual EMPLEADOS EMPLEADOS { get; set; }
    }
}
