//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public USUARIOS()
        {
            this.EMPLEADOS = new HashSet<EMPLEADOS>();
        }
    
        public string Usuario { get; set; }
        public string Contraseña { get; set; }
        public int Rol { get; set; }
        public int Estado { get; set; }
    
        public virtual ICollection<EMPLEADOS> EMPLEADOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual USUARIOS_TIPOS USUARIOS_TIPOS { get; set; }
    }
}
