//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOS
    {
        public VEHICULOS()
        {
            this.IMAGENES = new HashSet<IMAGENES>();
            this.RESERVAS = new HashSet<RESERVAS>();
            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int VEH_ID { get; set; }
        public Nullable<int> SUC_ID { get; set; }
        public string VEH_MARCA { get; set; }
        public string VEH_MODELO { get; set; }
        public string VEH_VERSION { get; set; }
        public Nullable<int> VEH_CILINDRADAS { get; set; }
        public string VEH_COLOR { get; set; }
        public Nullable<int> VEH_KILOMETROS { get; set; }
        public string VEH_DETALLES { get; set; }
        public string VEH_PUERTAS { get; set; }
        public string VEH_TIPOCOMBUSTIBLE { get; set; }
        public Nullable<int> VEH_AÑO { get; set; }
        public string VEH_PATENTE { get; set; }
        public string VEH_TIPOVEHICULO { get; set; }
        public Nullable<bool> VEH_VIGENTE { get; set; }
        public Nullable<int> VEH_PRECIO_INGRESO { get; set; }
        public bool VEH_CIERRE { get; set; }
        public bool VEH_LLANTAS { get; set; }
        public bool VEH_AIRBAG { get; set; }
        public bool VEH_AIRE { get; set; }
        public bool VEH_LEVANTA_VIDRIOS { get; set; }
        public bool VEH_FRENOS_ABS { get; set; }
        public bool VEH_NEBLINEROS { get; set; }
        public bool VEH_ESPEJOS_AUTOM { get; set; }
        public bool VEH_ASIENTOS_CUERO { get; set; }
        public bool VEH_RUEDA_AUXILIAR { get; set; }
        public string VEH_STEREO_MODELO { get; set; }
        public string VEH_STEREO_CODIGO { get; set; }
        public int CLI_ID { get; set; }
        public int EMP_ID { get; set; }
        public int FEC_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual FECHAS FECHAS { get; set; }
        public virtual ICollection<IMAGENES> IMAGENES { get; set; }
        public virtual ICollection<RESERVAS> RESERVAS { get; set; }
        public virtual SUCURSALES SUCURSALES { get; set; }
        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
