//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VEHICULOS
    {
        public VEHICULOS()
        {

            this.VENTAS = new HashSet<VENTAS>();
        }
    
        public int VEH_ID { get; set; }
        public Nullable<int> SUC_ID { get; set; }
        public string VEH_MODELO { get; set; }
        public string VEH_VERSION { get; set; }
        public string VEH_CILINDRADA { get; set; }
        public string VEH_COLOR { get; set; }
        public string VEH_KILOMETROS { get; set; }
        public string VEH_DETALLES { get; set; }
        public string VEH_PUERTAS { get; set; }
        public Nullable<int> TCOM_ID { get; set; }
        public string VEH_AÑO { get; set; }
        public string VEH_PATENTE { get; set; }
        public Nullable<int> TV_ID { get; set; }
        public Nullable<bool> VEH_VIGENTE { get; set; }
        public Nullable<int> VEH_PRECIO_INGRESO { get; set; }
        public Nullable<bool> VEH_CIERRE { get; set; }
        public Nullable<bool> VEH_LLANTAS { get; set; }
        public Nullable<bool> VEH_AIRBAG { get; set; }
        public Nullable<bool> VEH_AIRE { get; set; }
        public Nullable<bool> VEH_LEVANTA_VIDRIOS { get; set; }
        public Nullable<bool> VEH_FRENOS_ABS { get; set; }
        public Nullable<bool> VEH_NEBLINEROS { get; set; }
        public Nullable<bool> VEH_ESPEJOS_AUTOM { get; set; }
        public Nullable<bool> VEH_ASIENTOS_CUERO { get; set; }
        public Nullable<bool> VEH_RUEDA_AUXILIAR { get; set; }
        public string VEH_STEREO_MODELO { get; set; }
        public string VEH_STEREO_CODIGO { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> FEC_ID { get; set; }
        public Nullable<int> MAR_ID { get; set; }
        public Nullable<int> IMG_ID { get; set; }
        public Nullable<int> ES_ID { get; set; }
        public Nullable<int> MON_ID { get; set; }
    
        public virtual CLIENTES CLIENTES { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual ESTADOS ESTADOS { get; set; }
        public virtual FECHAS FECHAS { get; set; }
        public virtual IMAGENES IMAGENES { get; set; }
        public virtual MARCAS MARCAS { get; set; }
        public virtual MONEDAS MONEDAS { get; set; }
        public virtual SUCURSALES SUCURSALES { get; set; }

        public virtual ICollection<VENTAS> VENTAS { get; set; }
    }
}
