
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Octopus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VENTAS
{

    public int VEN_ID { get; set; }

    public Nullable<int> VEH_ID { get; set; }

    public Nullable<int> CLI_ID { get; set; }

    public Nullable<int> EMP_ID { get; set; }

    public Nullable<int> SUC_ID { get; set; }

    public Nullable<int> FEC_ID { get; set; }

    public Nullable<decimal> VEN_VALOR { get; set; }

    public Nullable<int> VEN_ESTADO { get; set; }

    public Nullable<int> RES_ID { get; set; }

    public bool VEN_VEH_ENT_USADO { get; set; }

    public string VEN_VEH_PAT_USADO { get; set; }

    public Nullable<decimal> VEN_VEH_VAL_USADO { get; set; }

    public Nullable<int> VEN_VEH_MAR_ID_USADO { get; set; }

    public string VEN_VEH_MOD_USADO { get; set; }

    public Nullable<int> VEN_VEH_ANIO_USADO { get; set; }



    public virtual CLIENTES CLIENTES { get; set; }

    public virtual EMPLEADOS EMPLEADOS { get; set; }

    public virtual FECHAS FECHAS { get; set; }

    public virtual MARCAS MARCAS { get; set; }

    public virtual SUCURSALES SUCURSALES { get; set; }

    public virtual VEHICULOS VEHICULOS { get; set; }

}

}
