//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Octopus.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VENTAS
    {
        public VENTAS()
        {
            this.ENTREGAS = new HashSet<ENTREGAS>();
        }
    
        public int VEN_ID { get; set; }
        public Nullable<int> FEC_ID { get; set; }
        public Nullable<int> CLI_ID { get; set; }
        public Nullable<int> VEH_ID { get; set; }
        public Nullable<int> EMP_ID { get; set; }
        public Nullable<int> MONTO { get; set; }
    
        public virtual ICollection<ENTREGAS> ENTREGAS { get; set; }
        public virtual FECHAS FECHAS { get; set; }
        public virtual EMPLEADOS EMPLEADOS { get; set; }
        public virtual VEHICULOS VEHICULOS { get; set; }
        public virtual CLIENTES CLIENTES { get; set; }
    }
}
