
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Octopus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_MARCAS
{

    public int VW_MAR_ID { get; set; }

    public string VW_MAR_DESCRIPCION { get; set; }

    public Nullable<int> VW_MAR_CUENTA { get; set; }

}

}
