
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Octopus.Models
{

using System;
    using System.Collections.Generic;
    
public partial class VW_Statistics
{

    public string Tipo { get; set; }

    public Nullable<int> CANTIDAD { get; set; }

}

}
